spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/mylbooks?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
#    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
  servlet:
    multipart:
      max-file-size: 20MB  #单个数据大小
      max-request-size: 100MB #总数据大小
#      content-type: text/html
mybatis:
  type-aliases-package: personal.moyilin.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml